### ISSUE TITLE
Missing Examples: i.e. for Renew Method

### ISSUE THREAD

**Issue by petzsch** [WHMCS/sample-provisioning-module#16]
According to https://developers.whmcs.com/provisioning-modules/supported-functions/ there is a Renew method that get's called as soon as a renewal invoice is paid.

However it's unclear what request parameters are available. I would need to know for example for how long I need to renew the hosting subscription. i.e. what the new expiry date should be.

Can you please update the example code to reflect this?

**Comment by WHMCSPeter** [comment]
Hi @petzsch - Sorry for the delay in response!

I can confirm that the following parameters as documented here would be provided:

https://developers.whmcs.com/provisioning-modules/module-parameters/

As you'll see, a `serviceid` attribute is returned. You will be able to retrieve the service and subsequently, it's configured billing cycle ('monthly', 'quarterly') etc... using the documented `\WHMCS\Service\Service` model:

https://classdocs.whmcs.com/8.4/WHMCS/Service/Service.html

I hope this provides you with the information you require to continue with your customisation. For further support, please use the official Developer Corner over at https://whmcs.community.
