### ISSUE TITLE
Are language overrides possible?

### ISSUE THREAD

**Issue by eugenevdm** [WHMCS/sample-provisioning-module#17]
I would like to know if language override are possible on provisioning modules, and if so, where to store them?

**Comment by WHMCSPeter** [comment]
Hello @eugenevdm,

Thanks for reaching out. There is not currently a way to provide translatable language strings in Provisioning Modules however, this is something you could implement yourself. For example, the following could allow you to load your own language files from `~/whmcs/modules/servers/provisioningmodule/lang/`:

```
function provisioningmodule_getLanguage(string $language = 'english')
{
    $languageArray = [];
    $defaultLang = 'english';
    $directory = implode(
        DIRECTORY_SEPERATOR,
        [
            ROOTDIR,
            'modules',
            'servers',
            'provisioningmodule', // Change this to your provisioning module folder name.
            'lang',
        ]
    );

    $directory .= DIRECTORY_SEPERATOR;

    $file = function (string $fileName) use ($directory) {
        return $directory . strtolower(trim($language)) . '.php';
    }

    if (!file_exists($file($language))) {
        // The selected lang file does not exist. Try falling back.
        if (!file_exists($file($defaultLang)) {
            throw new \Exception('Selected language and fallback not found');
        }

        $language = $fallbackLang;
    }

    $languageArray = include($file($language));

    return $languageArray;
}
```

Your lang file would need to return an array like so:
```
<?php

return [
    'myLangKey' => 'Hello World!',
    'anotherLangKey' => 'More Hello Worlds!',
];

```

In your module, you can then use:
```
$lang = provisioningmodule_getLanguage('french');
```

As long as you pass this along to any output in a vriable such as `$lang`, you should find the following works:
```
echo $lang['myLangKey']; // Outputs: Hello World!

echo $lang['anotherLangKey']; // Outputs: More Hello Worlds!
```

I trust this gives you plenty of information to achieve your requirements. WHMCS typically cannot provide support for third-party customisations and as such, this information is provided personally by me, with no guarantee or warranty at all. It is provided as-is and has not been tested for correctness.

Should you have any further questions, please do feel free to reach out in the Developer Corner over at https://whmcs.community which is the official support route for customisation questions.

Thanks!

Peter
