### ISSUE TITLE
Change params in _CreateAccount(array $params)

### ISSUE THREAD

**Issue by jordandegea** [WHMCS/sample-provisioning-module#3]
In my provisioning module, i want to create an object in a database. 
I have to save the objectId of this object for downgrade/upgrades for example. 

How can i save a new field in this function ?

**Comment by ShaunR** [comment]
Can you provide more information on what your trying to do exactly?

Any changes you make to $params is going to be reset the next time a provisioning module function is called.  Unless of course your accessing a WHMCS model  (I cant remember if any of those are passed in params) in which case you may be able to modify the entry by changing the value and then issueing $object->save();

Kind of need more info on what your trying to do.

**Comment by jassim90** [comment]
&&&&&
