### ISSUE TITLE
ConfigOptions missing input parameters

### ISSUE THREAD

**Issue by skechboy** [WHMCS/sample-provisioning-module#4]
The provisioningmodule_ConfigOptions function don't have input parameters, or not at least the full list of them.

It will be very easy for the developers if some of the server connection parameters are passed in this function to, so we could avoid manually fetching server connection data and decryption it's password.

**Comment by ShaunR** [comment]
This is the wrong place to be asking for this, you probably should open a ticket with WHMCS regarding this.  I agree though, ConfigOptions should receive an array of data.  Product information, group information, module info, etc.
