### ISSUE TITLE
UpdateModuleConfiguration on Provisioning Module?

### ISSUE THREAD

**Issue by sabmark** [WHMCS/sample-provisioning-module#6]
Hello,

Is there any way we can update Provisioning Module's Configuration Options programmatically? Like querying localAPI

Something Like
```
$command = 'UpdateModuleConfiguration';

$post_data = array(
    'moduleType' => 'provisioning',
    'moduleName' => 'modulename',
    'parameters[configoption1]' => 'some new value'
);

$admin_username = 'admin';

$result = localAPI($command, $post_data, $admin_username);

```

Thanks!

**Comment by x011** [comment]
WHMCS help around here seem to be 0.

**Comment by mattpugh** [comment]
Github issues are not actively monitored for support related questions. For support, please contact our support team via www.whmcs.com/support
